# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformCLI@2
  displayName: INIT
  inputs:
    command: 'init'
    allowTelemetryCollection: false

- task: TerraformCLI@2
  displayName: Plan
  inputs:
    command: 'plan'
    environmentServiceName: 'spn-azure-devops'
    allowTelemetryCollection: false

- task: TerraformCLI@2
  displayName: Apply
  inputs:
    command: 'apply'
    environmentServiceName: 'spn-azure-devops'
    allowTelemetryCollection: false